name       : cpphs
version    : 1.20.8
release    : 2
source     :
    - https://hackage.haskell.org/package/cpphs-1.20.8/cpphs-1.20.8.tar.gz : e56d64a7d8058e0fb63f0669397c1c861efb20a0376e0e74d86942ac151105ae
license    : LGPL-2.0
component  : programming.haskell
summary    : Cpphs is a re-implementation of the C pre-processor
description: |
    Cpphs is a re-implementation of the C pre-processor that is both more compatible with Haskell, and itself written in Haskell so that it can be distributed with compilers.
builddeps  :
    - haskell-cabal-install
    - haskell-old-locale
    - haskell-old-time
    - haskell-polyparse
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
