name       : cpphs
version    : 1.20.4
release    : 1
source     :
    - http://hackage.haskell.org/package/cpphs-1.20.4/cpphs-1.20.4.tar.gz : d159437cea89854c3f413f7157f40ea2d82272fce83efe6ce17e2065883da47e
license    : LGPL-2.0
component  : programming.haskell
summary    : Cpphs is a re-implementation of the C pre-processor
description: |
    Cpphs is a re-implementation of the C pre-processor that is both more compatible with Haskell, and itself written in Haskell so that it can be distributed with compilers.
builddeps  :
    - haskell-cabal-install
    - haskell-old-locale
    - haskell-old-time
    - haskell-polyparse
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
