name       : cpphs
version    : 1.20.9
release    : 3
source     :
    - https://hackage.haskell.org/package/cpphs-1.20.9/cpphs-1.20.9.tar.gz : 978df2ae7143f2ddf9b1354370373ed104357845401b50001dca1c1cd30c0b1f
license    : LGPL-2.1-or-later
component  : programming.haskell
summary    : Cpphs is a re-implementation of the C pre-processor
description: |
    Cpphs is a re-implementation of the C pre-processor that is both more compatible with Haskell, and itself written in Haskell so that it can be distributed with compilers.
builddeps  :
    - haskell-cabal-install
    - haskell-polyparse-devel
rundeps    :
    - devel:
        - haskell-polyparse-devel
networking : yes
setup      : |
    %cabal_configure -f -old-locale
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
